Conectar con google Drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

Leer archivos desde mi Drive y cargar los archivos

In [4]:
ruta = "/content/drive/MyDrive/Practica1"

cb = pd.read_csv("/content/drive/MyDrive/Practica1/afluencia_desglosada_cb_03_2025.csv")
tl = pd.read_csv("/content/drive/MyDrive/Practica1/afluencia_desglosada_tl_03_2025.csv")
trolebus = pd.read_csv("/content/drive/MyDrive/Practica1/afluencia_desglosada_trolebus_03_2025.csv")

Tipo de transporte

In [5]:
cb["tipo"] = "Cablebús"
tl["tipo"] = "Tren Ligero"
trolebus["tipo"] = "Trolebús"

Concatenar en un solo dataframe

In [6]:
df_total = pd.concat([cb, tl, trolebus], ignore_index=True)
df_total.head()

        fecha    mes  anio    linea  tipo_pago  afluencia      tipo
0  2022-01-01  Enero  2022  Línea 1    Prepago    24975.0  Cablebús
1  2022-01-01  Enero  2022  Línea 1  Gratuidad     2175.0  Cablebús
2  2022-01-01  Enero  2022  Línea 2    Prepago    42050.0  Cablebús
3  2022-01-01  Enero  2022  Línea 2  Gratuidad     3920.0  Cablebús
4  2022-01-02  Enero  2022  Línea 1    Prepago    31814.0  Cablebús

In [12]:
print(df_total.columns.tolist())

['fecha', 'mes', 'anio', 'linea', 'tipo_pago', 'afluencia', 'tipo']

Merge usando tipo_pago

In [16]:
df_pagos = pd.DataFrame({
    'tipo_pago': ['Prepago', 'Gratuita'],
    'descripcion': ['Pago con tarjeta', 'Acceso libre']
})

df_merged = pd.merge(df_total, df_pagos, on='tipo_pago', how='left')
df_merged.head()

,fecha,mes,anio,linea,tipo_pago,afluencia,tipo,descripcion
0,2022-01-01,Enero,2022,Línea 1,Prepago,24975.0,Cablebús,Pago con tarjeta
1,2022-01-01,Enero,2022,Línea 1,Gratuidad,2175.0,Cablebús,NaN
2,2022-01-01,Enero,2022,Línea 2,Prepago,42050.0,Cablebús,Pago con tarjeta
3,2022-01-01,Enero,2022,Línea 2,Gratuidad,3920.0,Cablebús,NaN
4,2022-01-02,Enero,2022,Línea 1,Prepago,31814.0,Cablebús,Pago con tarjeta

Afluencia total por tipo de pago

In [17]:
df_merged.groupby('tipo_pago')['afluencia'].sum().reset_index()

   tipo_pago     afluencia
0     Boleto  6.135989e+07
1  Gratuidad  8.447759e+07
2    Prepago  3.595907e+08

Afluencia total por descripción del pago

In [18]:
df_merged.groupby('descripcion')['afluencia'].sum().reset_index()

        descripcion    afluencia
0  Pago con tarjeta  359590665.0

Afluencia por tipo de transporte y tipo de pago

In [19]:
df_merged.groupby(['tipo', 'tipo_pago'])['afluencia'].sum().reset_index()

          tipo  tipo_pago     afluencia
0     Cablebús  Gratuidad  1.456727e+07
1     Cablebús    Prepago  1.197524e+08
2  Tren Ligero  Gratuidad  7.855982e+06
3  Tren Ligero    Prepago  7.945671e+07
4     Trolebús     Boleto  6.135989e+07
5     Trolebús  Gratuidad  6.205434e+07
6     Trolebús    Prepago  1.603816e+08

Promedio de afluencia por tipo de pago

In [20]:
df_merged.groupby('tipo_pago')['afluencia'].mean().reset_index()

   tipo_pago     afluencia
0     Boleto   4585.598461
1  Gratuidad   4987.165237
2    Prepago  21228.565146